{{- if .Values.clusterissuerEnabled -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Values.ingressShim.defaultIssuerName }}
  labels:
    app: {{ template "cert-manager.name" . }}
    chart: {{ template "cert-manager.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  acme:
    {{- if eq .Values.ingressShim.defaultIssuerName "letsencrypt-prod" }}
    server: "https://acme-v02.api.letsencrypt.org/directory"
    {{- else if eq .Values.ingressShim.defaultIssuerName "letsencrypt-staging" }}
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    {{- else }}
    server: {{ .Values.letsencrypt.server }}
    {{- end }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Values.ingressShim.defaultIssuerName }}-account-key
    {{- if eq .Values.ingressShim.defaultACMEChallengeType "http01" }}
    http01: {}
    {{- else if eq .Values.ingressShim.defaultACMEChallengeType "dns01" }}
    dns01:
      providers:
      - name: dns01-default
        {{- $providerType := .Values.ingressShim.defaultACMEDNS01ChallengeProviderType -}}
        {{- with .Values.ingressShim.defaultACMEDNS01ChallengeProviderConfig }}
        {{- if eq $providerType "route53" }}
        route53:
          region: us-east-1
          accessKeyID: {{ accessKeyID }}
          secretAccessKeySecretRef:
            name: {{ secretAccessKeySecretRef.name }}
            key: {{ secretAccessKeySecretRef.key }}
        {{- end -}}
        {{- end -}}
    {{- end -}}
{{- end -}}
